spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mybatis?characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: lhbwyp_ems
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    filters: stat, wall, log4j
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update
  redis:
    port: 6379
    host:  127.0.0.1
    jedis:
      pool:
        max-idle: 20
        min-idle: 1
        max-active: 20
        max-wait: 60000
    password: 123456
    database: 0
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix:  .jsp
birt:
  outPutPath: /opt/test/
  filepath: /opt/test/
  suffix: /opt/test/
  log:
    location: /opt/test/

mail:
  smtp:
    auth: true
    service: smtp.qq.com
    port: 587
  from:
    address: 960758921@qq.com
    smtp:
      pwd: myihkkyvtxegbahg
    nickname: 坤哥
server:
  port: 80